# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  svcbackscratcher:
    image: svcbackscratcher
    build:
      context: .
      dockerfile: src/svc-backscratcher/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
